# Generated by Django 2.1.7 on 2024-05-30 08:02

# from django.db import migrations, models


# class Migration(migrations.Migration):

#     dependencies = [
#         ('lists', '0003_item_list'),
#     ]

#     operations = [
#         migrations.AlterField(
#             model_name='item',
#             name='id',
#             field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
#         ),
#         migrations.AlterField(
#             model_name='list',
#             name='id',
#             field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
#         ),
#     ]

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='list',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='lists.list'),
        ),
    ]